name: TelApp CI/CD

on:
  push:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: レポジトリをチェックアウト
        uses: actions/cjeckout@v3
      
      - name: Node.js環境をセットアップ
        uses: actions/setup-node@ve
        with:
          node-version: 16
          cache: npm
      
      - name: 関係モジュールをインストール
        run: npm ci
      
      - name: テストを実行
        run: npm run test:prod